version: 5.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_non_tags: false

image: Visual Studio 2015

shallow_clone: true

clone_depth: 1

clone_folder: C:\projects\vidcutter

environment:
  # APPVEYOR_RDP_PASSWORD:
  #   secure: cr6ouL4ybiiKClW/UJwM6g==
  APPVEYOR_SKIP_FINALIZE_ON_EXIT: false
  PYTHONUNBUFFERED: 1
  PYTHONHOME: C:\Python36-x86

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # ---------------------------------------- 64-bit build ----------------------------------------
  - set PATH=%PYTHONHOME%;%PYTHONHOME%\scripts;%PYTHONHOME%\tools\scripts;%PATH%
  - cd C:\projects\vidcutter
  - echo Installing latest pip + setuptools...
  - C:\Python36-x86\python.exe -m pip install -U pip setuptools
  - echo Installing PyQt5 and PyOpenGL C:\Python36-x86\python.exe wheels via pip...
  - C:\Python36-x86\python.exe -m pip install PyQt5 PyOpenGL PyOpenGL-accelerate PyInstaller xmltodict
  # - echo Installing latest git checkout of PyInstaller...
  # - C:\Python36-x86\python.exe -m pip install git+https://github.com/pyinstaller/pyinstaller.git@develop
  - echo Setting up libmpv build subfolders...
  - mkdir "_build\pyinstaller\temp"
  - mkdir "_build\pyinstaller\libmpv"
  - mkdir "_build\pyinstaller\libmpv\64"
  - echo Setup build environment for MSVC++
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - echo Build Cython/C extension for libmpv binding...
  - C:\Python36-x86\python.exe setup.py build_ext -i
  - appveyor PushArtifact vidcutter\libs\mpv.cp36-win_amd64.pyd
  - echo Retrieve URL for latest available version of libmpv
  - for /f "delims=" %%a in ('C:\Python36-x86\python.exe helpers.py get_latest_win32_libmpv_64') do @set LIBMPV=%%a
  - echo Downloading latest libmpv 64-bit build...
  # - curl -L -fsS -o _build\pyinstaller\temp\mpv-dev.7z https://mpv.srsfckn.biz/mpv-dev-20170718.7z
  - curl -L -fsS -o _build\pyinstaller\temp\mpv-dev.7z https://downloads.sourceforge.net/project/mpv-player-windows%LIBMPV%
  - cd _build/pyinstaller/temp
  - 7z e mpv-dev.7z mpv-1.dll -o"..\libmpv\64\"
  - echo Copy DLLs from Windows for ANGLE Direct3D engine support..
  - copy "C:\Windows\System32\d3dcompiler_43.dll" "..\libmpv\64\"
  - copy "C:\Windows\System32\d3dcompiler_47.dll" "..\libmpv\64\"
  - echo Freezing w/ PyInstaller
  - cd ..
  # - for /f "delims=" %%a in ('C:\Python36-x86\python.exe version.py') do @set APPVER=%%a
  - call build.pyinstaller.win.bat 64
  - echo.
  - cd ..\InnoSetup\Output
  - appveyor PushArtifact VidCutter-5.0.0-setup-win64.exe
  # ---------------------------------------- 32-bit build ----------------------------------------
  - cd ..\..\..
  - set PYTHONHOME=C:\Python36-x86
  - set PATH=%PYTHONHOME%;%PYTHONHOME%\scripts;%PYTHONHOME%\tools\scripts;%PATH%
  - echo Installing latest pip + setuptools...
  - C:\Python36-x86\python.exe -m pip install -U pip setuptools
  - echo Installing PyQt5 and PyOpenGL C:\Python36-x86\python.exe wheels via pip...
  - C:\Python36-x86\python.exe -m pip install PyQt5 PyOpenGL PyOpenGL-accelerate PyInstaller xmltodict
  # - echo Installing latest git checkout of PyInstaller...
  # - C:\Python36-x86\python.exe -m pip install git+https://github.com/pyinstaller/pyinstaller.git@develop
  - echo Setting up libmpv build subfolders...
  - mkdir "_build\pyinstaller\temp"
  - mkdir "_build\pyinstaller\libmpv"
  - mkdir "_build\pyinstaller\libmpv\32"
  - echo Setup build environment for MSVC++
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - echo Build Cython/C extension for libmpv binding...
  - C:\Python36-x86\python.exe setup.py build_ext -i
  # - appveyor PushArtifact vidcutter\libs\mpv.cp36-win32.pyd
  - echo Retrieve URL for latest available version of libmpv
  - for /f "delims=" %%a in ('C:\Python36-x86\python.exe helpers.py get_latest_win32_libmpv_32') do @set LIBMPV=%%a
  - echo Downloading latest libmpv 32-bit build...
  # - curl -L -fsS -o _build\pyinstaller\temp\mpv-dev.7z https://mpv.srsfckn.biz/mpv-dev-20170718.7z
  - curl -L -fsS -o _build\pyinstaller\temp\mpv-dev.7z https://downloads.sourceforge.net/project/mpv-player-windows%LIBMPV%
  - cd _build/pyinstaller/temp
  - 7z e mpv-dev.7z mpv-1.dll -o"..\libmpv\32\"
  - echo Copy DLLs from Windows for ANGLE Direct3D engine support..
  - copy "C:\Windows\SysWOW64\d3dcompiler_43.dll" "..\libmpv\32\"
  - copy "C:\Windows\SysWOW64\d3dcompiler_47.dll" "..\libmpv\32\"
  - echo Freezing w/ PyInstaller
  - cd ..
  # - for /f "delims=" %%a in ('C:\Python36-x86\python.exe version.py') do @set APPVER=%%a
  - call build.pyinstaller.win.bat 32
  - echo.
  - cd ..\InnoSetup\Output
  - appveyor PushArtifact VidCutter-5.0.0-setup-win32.exe
  # completion
  - echo.
  - echo SUCCESS
  - appveyor exit

nuget:
  disable_publish_on_pr: true

test: off

#artifacts:
# - path: '_build\InnoSetup\Output\VidCutter-*-setup-win64.exe'
#   name: Windows Installer
#   type: File
#
# - path: 'vidcutter\libs\*.pyd'
#   name: Extension Module
#   type: zip

# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


# deploy:
#   release: 4.0.0
#   description: '4.0.0 Pre-Release'
#   provider: GitHub
#   auth_token:
#     secure: 4GlXRbRHs73J4gCyirRNPtAN6MDQS+JetrPpS8JMo/9YJCK5Vpr7wLa6xKeIO46T
#   artifact: /.*\.exe/
#   draft: false
#   prerelease: true
#   force_update: true
#   on:
#     branch: master
#     appveyor_repo_tag: true


# --------------------------------------------------------------
# 
# on_finish:
#   - cd C:\projects\builds\
#   - git add -A
#   - git commit -am "AppVeyor Build Agent commit"
#   - git push
# - echo.
# - echo *** Building 32bit installer ***
# - echo.
# - 7z e mpv-dev.7z 32/mpv-1.dll -o"_build\pyinstaller\libmpv\32"
# - mkdir "_build\pyinstaller\libmpv\32"
# - echo Downloading latest libmpv 32-bit build...
# - curl -L -fsS -o _build\pyinstaller\temp\libmpv32.7z "https://downloads.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-i686-20170715-git-18c74f7.7z"
# - 7z e "_build\pyinstaller\temp\libmpv32.7z" mpv-1.dll -o"_build\pyinstaller\temp"
# - move "_build\pyinstaller\temp\mpv-1.dll" "_build\pyinstaller\libmpv\32"
# - copy "C:\Windows\SysWOW64\d3dcompiler_43.dll" "_build\pyinstaller\libmpv\32"
# - copy "C:\Windows\SysWOW64\d3dcompiler_47.dll" "_build\pyinstaller\libmpv\32"
