version: 4.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - feature/add-externals

image: Visual Studio 2015

shallow_clone: true

clone_depth: 1

clone_folder: C:\projects\vidcutter

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: uzV46p3oDwpGYncy5y+ysw==
  APPVEYOR_SKIP_FINALIZE_ON_EXIT: false
  PYTHONUNBUFFERED: 1
  PYTHONHOME: C:\Python36-x64

install:
  - set PATH=%PYTHONHOME%;%PYTHONHOME%\scripts;%PYTHONHOME%\tools\scripts;%PATH%
  - echo Installing latest pip + setuptools...
  - C:\Python36-x64\python.exe -m pip install -U pip setuptools
  - echo Installing PyQt5 and PyOpenGL C:\Python36-x64\python.exe wheels via pip...
  - C:\Python36-x64\python.exe -m pip install PyQt5 PyOpenGL PyOpenGL-accelerate
  - echo Installing latest git checkout of PyInstaller...
  - C:\Python36-x64\python.exe -m pip install git+https://github.com/pyinstaller/pyinstaller.git@develop
  - echo Setting up libmpv build subfolders...
  - mkdir "_build\pyinstaller\temp"
  - mkdir "_build\pyinstaller\libmpv"
  - mkdir "_build\pyinstaller\libmpv\64"
  - echo Setup build environment for MSVC++
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - echo Build Cython/C extension for libmpv binding...
  - C:\Python36-x64\python.exe setup.py build_ext -i
  - echo Downloading latest libmpv 64-bit build...
  - curl -L -fsS -o _build\pyinstaller\temp\libmpv64.7z "https://downloads.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-x86_64-20170715-git-18c74f7.7z"
  - 7z e "_build\pyinstaller\temp\libmpv64.7z" mpv-1.dll -o"_build\pyinstaller\temp"
  - move "_build\pyinstaller\temp\mpv-1.dll" "_build\pyinstaller\libmpv\64"
  - echo Copy DLLs from Windows for ANGLE Direct3D engine support..
  - copy "C:\Windows\System32\d3dcompiler_43.dll" "_build\pyinstaller\libmpv\64"
  - copy "C:\Windows\System32\d3dcompiler_47.dll" "_build\pyinstaller\libmpv\64"
  - echo Freezing app w/ PyInstaller
  - cd "_build\pyinstaller"
  - call build.pyinstaller.win.bat 64
  - echo.
  - if exist "C:\projects\vidcutter\_build\InnoSetup\Output\%OUTFILE%" (
      ren "C:\projects\vidcutter\_build\InnoSetup\Output\%OUTFILE%" "C:\projects\vidcutter\_build\InnoSetup\Output\VidCutter-%APPVER%-dev-setup-%BINARCH%.exe"
      appveyor PushArtifact "C:\projects\vidcutter\_build\InnoSetup\Output\VidCutter-%APPVER%-dev-setup-%BINARCH%.exe"
    )
  - echo.
  - echo SUCCESS
  - appveyor exit

nuget:
  disable_publish_on_pr: true

test: off

artifacts:
 - path: C:\projects\vidcutter\_build\InnoSetup\Output\VidCutter-*-dev-setup-*.exe
   name: Windows Installers
   type: File

on_finish:
  - cd C:\projects\vidcutter
  - git checkout gh-pages
  - git fetch && git rebase
  - git clean -fd
  - git submodule update --init --recursive
  - cd builds
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email "pete@ozmartians.com"
  - git config --global user.name "AppVeyor Build Agent"
  - copy C:\projects\vidcutter\_build\InnoSetup\Output\VidCutter-*-setup-*.exe .
  - git add -A
  - git commit -am "AppVeyor automated artifacts deployment"
  - git push
  - echo.
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# - path: C:\projects\vidcutter\_build\InnoSetup\Output\VidCutter-*-setup-x86.exe

  # - echo.
  # - echo *** Building 32bit installer ***
  # - echo.
  # - mkdir "_build\pyinstaller\libmpv\32"
  # - echo Downloading latest libmpv 32-bit build...
  # - curl -L -fsS -o _build\pyinstaller\temp\libmpv32.7z "https://downloads.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-i686-20170715-git-18c74f7.7z"
  # - 7z e "_build\pyinstaller\temp\libmpv32.7z" mpv-1.dll -o"_build\pyinstaller\temp"
  # - move "_build\pyinstaller\temp\mpv-1.dll" "_build\pyinstaller\libmpv\32"
  # - copy "C:\Windows\SysWOW64\d3dcompiler_43.dll" "_build\pyinstaller\libmpv\32"
  # - copy "C:\Windows\SysWOW64\d3dcompiler_47.dll" "_build\pyinstaller\libmpv\32"
