version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - feature/add-externals

image: Visual Studio 2015

shallow_clone: true

clone_depth: 1

clone_folder: C:\projects\vidcutter

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: uzV46p3oDwpGYncy5y+ysw==
  PYTHONUNBUFFERED: 1
  PYTHON: C:\Python36\python.exe

install:
- cmd: >-
    set PATH=%PATH%;C:\Python36
    
    rem Installing latest pip + setuptools...
    %PYTHON% -m pip install -U pip setuptools

    rem Installing PyQt5 and PyOpenGL python wheels via pip...
    %PYTHON% -m pip install PyQt5 PyOpenGL PyOpenGL-accelerate

    rem Installing latest git checkout of PyInstaller...
    %PYTHON% -m pip install git+https://github.com/pyinstaller/pyinstaller.git

    rem Setting up libmpv build subfolders...
    mkdir "_build\pyinstaller\temp"
    mkdir "_build\pyinstaller\libmpv"
    mkdir "_build\pyinstaller\libmpv\32"
    mkdir "_build\pyinstaller\libmpv\64"

    rem Downloading latest libmpv 32-bit build...
    @powershell Invoke-WebRequest "https://downloads.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-i686-20170715-git-18c74f7.7z" -OutFile "_build\pyinstaller\temp\libmpv32.7z"
    7z e "_build\pyinstaller\temp\libmpv32.7z" mpv-1.dll -o"_build\pyinstaller\temp"
    move "_build\pyinstaller\temp\mpv-1.dll" "_build\pyinstaller\libmpv\32"

    rem Downloading latest libmpv 64-bit build...
    @powershell Invoke-WebRequest "https://downloads.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-x86_64-20170715-git-18c74f7.7z" -OutFile "_build\pyinstaller\temp\libmpv64.7z"
    7z e "_build\pyinstaller\temp\libmpv64.7z" mpv-1.dll -o"_build\pyinstaller\temp"
    move "_build\pyinstaller\temp\mpv-1.dll" "_build\pyinstaller\libmpv\64"

    rem Copy DLLs from Windows for ANGLE Direct3D engine support..
    copy "C:\Windows\SysWOW64\d3dcompiler_43.dll" "_build\pyinstaller\libmpv\32"
    copy "C:\Windows\SysWOW64\d3dcompiler_47.dll" "_build\pyinstaller\libmpv\32"
    copy "C:\Windows\System32\d3dcompiler_43.dll" "_build\pyinstaller\libmpv\64"
    copy "C:\Windows\System32\d3dcompiler_47.dll" "_build\pyinstaller\libmpv\64"

    rem Verify libmpv folder is correct...
    dir /S "_build\pyinstaller\libmpv"

nuget:
  disable_publish_on_pr: true

build_script:
- cmd: >-
    rem Build Cython/C extension for libmpv binding...
    %PYTHON% setup.py build_ext -i

    rem Listing "mpv.*.pyd" files from libs folder to double check it was built via logs...
    dir vidcutter\libs\mpv.*.pyd

    rem All building complete!
    rem SUCCESS

test: off

deploy: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
