version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - feature/add-externals

image: Visual Studio 2015

shallow_clone: true

clone_depth: 1

clone_folder: C:\projects\vidcutter

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: uzV46p3oDwpGYncy5y+ysw==
  PYTHONUNBUFFERED: 1
  PYTHONHOME: C:\Python36-x64

install:
  - set PATH=%PYTHONHOME%;%PYTHONHOME%\scripts;%PYTHONHOME%\tools\scripts;%PATH%
  - echo Installing latest pip + setuptools...
  - C:\Python36-x64\python.exe -m pip install -U pip setuptools
  - echo Installing PyQt5 and PyOpenGL C:\Python36-x64\python.exe wheels via pip...
  - C:\Python36-x64\python.exe -m pip install PyQt5 PyOpenGL PyOpenGL-accelerate
  - echo Installing latest git checkout of PyInstaller...
  - C:\Python36-x64\python.exe -m pip install git+https://github.com/pyinstaller/pyinstaller.git
  - echo Setting up libmpv build subfolders...
  - mkdir "_build\pyinstaller\temp"
  - mkdir "_build\pyinstaller\libmpv"
  - echo.
  - echo *** Building 64bit installer ***
  - echo.
  - mkdir "_build\pyinstaller\libmpv\64"
  - echo Downloading latest libmpv 64-bit build...
  - curl -L -fsS -o _build\pyinstaller\temp\libmpv64.7z "https://downloads.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-x86_64-20170715-git-18c74f7.7z"
  - 7z e "_build\pyinstaller\temp\libmpv64.7z" mpv-1.dll -o"_build\pyinstaller\temp"
  - move "_build\pyinstaller\temp\mpv-1.dll" "_build\pyinstaller\libmpv\64"
  - echo Copy DLLs from Windows for ANGLE Direct3D engine support..
  - copy "C:\Windows\System32\d3dcompiler_43.dll" "_build\pyinstaller\libmpv\64"
  - copy "C:\Windows\System32\d3dcompiler_47.dll" "_build\pyinstaller\libmpv\64"
  - echo Freezing app w/ PyInstaller
  - cd "_build\pyinstaller"
  - call build.pyinstaller.win.bat 64
  # - echo.
  # - echo *** Building 32bit installer ***
  # - echo.
  # - mkdir "_build\pyinstaller\libmpv\32"
  # - echo Downloading latest libmpv 32-bit build...
  # - curl -L -fsS -o _build\pyinstaller\temp\libmpv32.7z "https://downloads.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-i686-20170715-git-18c74f7.7z"
  # - 7z e "_build\pyinstaller\temp\libmpv32.7z" mpv-1.dll -o"_build\pyinstaller\temp"
  # - move "_build\pyinstaller\temp\mpv-1.dll" "_build\pyinstaller\libmpv\32"
  # - copy "C:\Windows\SysWOW64\d3dcompiler_43.dll" "_build\pyinstaller\libmpv\32"
  # - copy "C:\Windows\SysWOW64\d3dcompiler_47.dll" "_build\pyinstaller\libmpv\32"

nuget:
  disable_publish_on_pr: true

build_script:
  - echo Setup build environment for MSVC++
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - echo Build Cython/C extension for libmpv binding...
  - C:\Python36-x64\python.exe setup.py build_ext -i
  - echo Listing "mpv.*.pyd" files from libs folder to double check it was built via logs...
  - dir vidcutter\libs\mpv.*.pyd
  - echo.
  - echo All building complete!
  - echo SUCCESS

test: off

deploy: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# artifacts:
#   - path