#######################################################################
#
# VidCutter - media cutter & joiner
#
# copyright © 2017 Pete Alexandrou
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#######################################################################

language: python
os: linux
dist: trusty
group: edge
sudo: required
python: '3.5'
git:
  depth: 3

before_install:
  - sudo rm -f /var/lib/dpkg/lock >/dev/null 2>&1
  - sudo apt-get install python-dev libffi-dev libssl-dev
  - sudo pip install requests[security]
  - sudo apt-get install libncurses5 libgcc1 libstdc++6 libc6 libx11-6 libxext6 libxrender1 libice6 libsm6 libgl1-mesa-glx libglib2.0-0 -y
  - sudo add-apt-repository ppa:mc3man/testing6 -y
  # - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get -qq update
  - echo "Installing Qt5.8 libs..."
  - sudo apt-get install -y qt58-meta-full
  - echo "Installing multimedia runtime libs + python OpenGL bindings..."
  - sudo apt-get install -y libmpv-dev libmpv1 python3-dev python3-setuptools ffmpeg mediainfo
  - sudo pip install -qq pyopengl pyopengl_accelerate
  - echo "Building sip..."
  - wget https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.2/sip-4.19.2.tar.gz
  - tar -xzvf sip-4.19.2.tar.gz
  - pushd sip-4.19.2 && python ./configure.py && make && sudo make install && popd
  - echo "Building PyQt5..."
  - wget https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.8.2/PyQt5_gpl-5.8.2.tar.gz
  - tar -xzvf PyQt5_gpl-5.8.2.tar.gz
  - pushd PyQt5_gpl-5.8.2 && source /opt/qt58/bin/qt58-env.sh && python ./configure.py --confirm-license && make && sudo make install && popd

install:
  - sed -i "s/pypi/deb/" "vidcutter/__init__.py"
  - sudo python setup.py install

script: echo "Done!"

notifications:
  email: false


# deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: ozmartian
#  password:
#    secure: hqZow36uoK8oGIScjj5VmvFkyrfpbxRTFx1tLZfp+kTjmCMfG3k6kFgcKCKskQGVofWNynMCH30iKuF07K5vMUFv+BrxBDKDw07bcWJ6UfW7vuDNsOosU3eRShzBBUsK9v90TCCFDFIFg4oImw6vvXYM1jO+fsO05quDEoZ4vHvVjaP+xri6h8P37h0swR2sQpOSh+JNaxYGLUQZWgXRlBVXCo0ShZs/iqixLaIVfNxKI/scGmO8KN4lk8mpw8q+jojS60VbzpvPZSu88Z4U2ndGQyhV1b2CJ96FPBnaofJNvKFIRx4sar8E7PIgy8lN7ZinDgFVO20JBLXEnTfR/qsOsrQKfpzSwQ2YSAaLua0MXTsTKam/tizVqW8AIyxoI2OEHaJ6tkUmOO31AgKvYBV74oaEp231/jdDHe2DqtOT+KmVB0kx7tnVOi48AhfXQA88jIhMFOjjobytDMBoGXXEjtshwAB1rS4ZadeFQHTKWbCvM53Btxggj9piipLbm0Wt1bf/sRtQEunVAtbRd74XQljsQyazcowafSnbImpUgCTGWJYYDM60mC1FxNZ6d8DEp9B+y0YFh9ajaTPn+DVDBkCEmeMSegtSCqDtdbj4GV1P2Aw3L3UcTP+SiHAF9VKz9Ga8Z6EsMVirbPR43TNXdcaSAGFSUANq0eKNwzw=
#  on:
#    branch: master
#    tags: true
