name: vidcutter
version: 5.0.5
summary: the simplest + fastest video cutter & joiner
description: |
    A modern, simple to use, constantly evolving and 
    hella fast MEDIA CUTTER + JOINER w/ frame-accurate
    SmartCut technology + Qt5, libmpv, FFmpeg and
    MediaInfo powering the backend.
icon: data/icons/vidcutter.png
grade: devel
confinement: devmode

apps:
  vidcutter:
    command: desktop-launch vidcutter
    plugs: [home, pulseaudio, x11, opengl]
    desktop: data/desktop/vidcutter.desktop

parts:
  vidcutter:
    plugin: python
    process-dependency-links: false
    after: [desktop-qt5]
    build-packages:
        - python3-dev
        - python3-setuptools
        - libmpv-dev
    stage-packages:
        - python3-pyqt5
        - libmpv1
        - ffmpeg
        - mediainfo
